services:
  postgres:
    image: postgres
    container_name: inbazz-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inbazz-challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inbazz-challenge"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-test:
    image: postgres:15-alpine
    container_name: inbazz-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inbazz-challenge-test
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inbazz-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/inbazz-challenge"
      TEST_DATABASE_URL: "postgresql://postgres:postgres@postgres-test:5432/inbazz-challenge-test"
      PORT: 3000
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
